import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { InsertionRecord } from './types';
import { detectLargeInsertion } from './insertionDetector';
import { BlockTracker } from './blockTracker';
import { DataStore } from './dataStore';
import { SupabaseClient } from './supabaseClient';

function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
}

async function askParticipantId(context: vscode.ExtensionContext): Promise<string> {
  const input = await vscode.window.showInputBox({
    title: 'AI Code Research Tracker — Participant ID',
    prompt: 'Enter your participant ID (provided by the researcher)',
    placeHolder: 'e.g. P01',
    ignoreFocusOut: true,
    validateInput: v => (v.trim().length === 0 ? 'Participant ID cannot be empty' : null)
  });
  const id = (input ?? '').trim() || 'unknown';
  await context.globalState.update('participantId', id);
  return id;
}

let tracker: BlockTracker;
let dataStore: DataStore;
let supabase: SupabaseClient;
let participantId: string | null = null;
let statusBarItem: vscode.StatusBarItem;
let pendingRecordId: string | null = null;
let reviewTimerInterval: ReturnType<typeof setInterval> | null = null;
let saveTimer: ReturnType<typeof setTimeout> | null = null;

export async function activate(context: vscode.ExtensionContext): Promise<void> {
  tracker = new BlockTracker();
  dataStore = new DataStore(context);
  supabase = new SupabaseClient();
  // Clear stale pendingConfirmation records from previous sessions — they can never be resolved
  const saved = dataStore.load().filter(r => !r.pendingConfirmation);
  tracker.loadAll(saved);

  participantId = context.globalState.get<string>('participantId') ?? null;
  if (!participantId || participantId === 'unknown') {
    participantId = await askParticipantId(context);
  }

  statusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Right, 100);
  statusBarItem.command = 'aiTracker.acceptCode';
  context.subscriptions.push(statusBarItem);

  context.subscriptions.push(
    vscode.commands.registerCommand('aiTracker.acceptCode', handleAccept),
    vscode.commands.registerCommand('aiTracker.viewStats', showStats),
    vscode.commands.registerCommand('aiTracker.exportCSV', exportCSV),
    vscode.commands.registerCommand('aiTracker.setParticipantId', async () => {
      participantId = await askParticipantId(context);
      vscode.window.showInformationMessage(`[AI Tracker] Participant ID set to: ${participantId}`);
    })
  );

  context.subscriptions.push(
    vscode.workspace.onDidChangeTextDocument(event => {
      const detected = detectLargeInsertion(event);
      if (detected && !pendingRecordId) {
        const id = generateId();
        const record: InsertionRecord = {
          id,
          insertionTimestamp: Date.now(),
          fileUri: event.document.uri.toString(),
          fileName: path.basename(event.document.uri.fsPath),
          originalLineCount: detected.lineCount,
          startLine: detected.startLine,
          endLine: detected.endLine,
          pendingConfirmation: true,
          pendingAcceptance: false,
          editedBeforeAcceptance: false,
          wantsToModify: null,
          reviewStartTimestamp: null,
          reviewDurationMs: null,
          condition: null,
          acceptanceTimestamp: null,
          observationWindowEndTimestamp: null,
          postAcceptance: {
            editSessions: [],
            changedAbsoluteLines: [],
            totalLinesChanged: 0,
            proportionLinesChanged: 0,
            changeFrequency: 0,
            totalActiveModificationTimeMs: 0,
            timeToFirstModificationMs: null
          }
        };
        tracker.add(record);
        pendingRecordId = id;
        promptUser(id, detected.lineCount).catch(err => {
          console.error('[AITracker] promptUser error:', err);
          tracker.remove(id);
          pendingRecordId = null;
        });
      }

      tracker.handleDocumentChange(event, record => {
        scheduleSave();
        syncToSupabase(record);
      });
    })
  );

  console.log(`[AITracker] Activated — participant: ${participantId}`);
}

async function promptUser(id: string, lineCount: number): Promise<void> {
  // Step 1: Was this AI-generated?
  const aiAnswer = await vscode.window.showInformationMessage(
    `Code insertion detected (${lineCount} line${lineCount > 1 ? 's' : ''}). Was this generated by an AI tool (e.g. GitHub Copilot, ChatGPT)?`,
    { modal: true },
    'Yes, AI-generated',
    'No'
  );

  if (aiAnswer !== 'Yes, AI-generated') {
    tracker.remove(id);
    pendingRecordId = null;
    return;
  }

  tracker.confirmAI(id);
  const record = tracker.get(id);
  if (!record) return;
  record.pendingAcceptance = true;

  // Step 2: Do you want to modify?
  const modifyAnswer = await vscode.window.showInformationMessage(
    'Do you want to modify this code before accepting?',
    { modal: true },
    'Yes, I\'ll review',
    'No, accept now'
  );

  if (modifyAnswer === 'Yes, I\'ll review') {
    record.wantsToModify = true;
    record.reviewStartTimestamp = Date.now();
    startReviewTimer(id);
    statusBarItem.backgroundColor = new vscode.ThemeColor('statusBarItem.warningBackground');
  } else {
    // Immediate condition — accept right away
    record.wantsToModify = false;
    record.condition = 'immediate';
    record.reviewDurationMs = 0;
    statusBarItem.backgroundColor = undefined;
    vscode.window.showInformationMessage('[AI Tracker] Accepted (Immediate).');
    tracker.accept(id);
    syncToSupabase(record);
    pendingRecordId = null;
    statusBarItem.hide();
    scheduleSave();
    return;
  }

  statusBarItem.show();
  scheduleSave();
}

function startReviewTimer(id: string): void {
  updateStatusBar(id);
  reviewTimerInterval = setInterval(() => updateStatusBar(id), 1000);
}

function updateStatusBar(id: string): void {
  const record = tracker.get(id);
  if (!record || !record.reviewStartTimestamp) return;

  const elapsed = Math.floor((Date.now() - record.reviewStartTimestamp) / 1000);
  const mm = Math.floor(elapsed / 60).toString().padStart(2, '0');
  const ss = (elapsed % 60).toString().padStart(2, '0');

  statusBarItem.text = `$(check) Accept AI Code  |  ${mm}:${ss}`;
  statusBarItem.tooltip = 'Click when done reviewing. Timer shows how long you\'ve been modifying.';
}

function stopReviewTimer(): void {
  if (reviewTimerInterval) {
    clearInterval(reviewTimerInterval);
    reviewTimerInterval = null;
  }
}

async function handleAccept(): Promise<void> {
  if (!pendingRecordId) {
    vscode.window.showInformationMessage('[AI Tracker] No pending AI code block.');
    return;
  }

  const record = tracker.get(pendingRecordId);
  if (record && record.reviewStartTimestamp) {
    record.reviewDurationMs = Date.now() - record.reviewStartTimestamp;
  }

  stopReviewTimer();
  tracker.accept(pendingRecordId);

  const updated = tracker.get(pendingRecordId);
  if (updated) {
    const label = updated.condition === 'reviewed' ? 'Reviewed' : 'Immediate';
    const duration = updated.reviewDurationMs
      ? ` (review time: ${Math.round(updated.reviewDurationMs / 1000)}s)`
      : '';
    vscode.window.showInformationMessage(
      `[AI Tracker] Accepted (${label})${duration}. Tracking modifications for 7 days.`
    );
    syncToSupabase(updated);
  }

  pendingRecordId = null;
  statusBarItem.hide();
  scheduleSave();
}

function showStats(): void {
  const all = tracker.getAll().filter(r => r.condition !== null);

  if (all.length === 0) {
    vscode.window.showInformationMessage('[AI Tracker] No accepted blocks recorded yet.');
    return;
  }

  const reviewed = all.filter(r => r.condition === 'reviewed');
  const immediate = all.filter(r => r.condition === 'immediate');

  function avg(arr: InsertionRecord[], fn: (r: InsertionRecord) => number): string {
    return arr.length
      ? (arr.reduce((s, r) => s + fn(r), 0) / arr.length).toFixed(3)
      : 'N/A';
  }

  const lines = [
    `Participant: ${participantId}`,
    `Total accepted blocks: ${all.length}`,
    `  Reviewed: ${reviewed.length}   Immediate: ${immediate.length}`,
    ``,
    `Avg review duration (ms):`,
    `  Reviewed:  ${avg(reviewed, r => r.reviewDurationMs ?? 0)}`,
    ``,
    `Proportion lines changed (avg):`,
    `  Reviewed:  ${avg(reviewed, r => r.postAcceptance.proportionLinesChanged)}`,
    `  Immediate: ${avg(immediate, r => r.postAcceptance.proportionLinesChanged)}`,
    ``,
    `Change frequency (avg):`,
    `  Reviewed:  ${avg(reviewed, r => r.postAcceptance.changeFrequency)}`,
    `  Immediate: ${avg(immediate, r => r.postAcceptance.changeFrequency)}`,
    ``,
    `Active modification time ms (avg):`,
    `  Reviewed:  ${avg(reviewed, r => r.postAcceptance.totalActiveModificationTimeMs)}`,
    `  Immediate: ${avg(immediate, r => r.postAcceptance.totalActiveModificationTimeMs)}`
  ].join('\n');

  vscode.window.showInformationMessage(lines, { modal: true });
}

async function exportCSV(): Promise<void> {
  const records = tracker.getAll();
  const csv = dataStore.buildCSV(records);

  const uri = await vscode.window.showSaveDialog({
    defaultUri: vscode.Uri.file(`ai-tracker-${participantId ?? 'data'}.csv`),
    filters: { CSV: ['csv'] }
  });

  if (!uri) return;

  fs.writeFileSync(uri.fsPath, csv, 'utf8');
  vscode.window.showInformationMessage(`[AI Tracker] Exported to ${uri.fsPath}`);
}

function syncToSupabase(record: InsertionRecord): void {
  if (!participantId) return;
  supabase.sync(record, participantId).catch(err =>
    console.error('[AITracker] Supabase sync failed:', err)
  );
}

function scheduleSave(): void {
  if (saveTimer) clearTimeout(saveTimer);
  saveTimer = setTimeout(() => dataStore.save(tracker.getAll()), 2000);
}

export function deactivate(): void {
  stopReviewTimer();
  if (saveTimer) {
    clearTimeout(saveTimer);
    dataStore.save(tracker.getAll());
  }
}
